version: '3.4'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: correspondence
  storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    ports:
      - "10000:10000"
      - "10001:10001"
    healthcheck:
        test: nc 127.0.0.1 10000 -z
        interval: 1s
        retries: 30
  storage_init:
      image: mcr.microsoft.com/azure-cli:latest
      command:
          - /bin/sh
          - -c
          - |
              az storage container create --name attachments
      depends_on:
          storage:
              condition: service_healthy
      environment:
          AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://storage:10000/devstoreaccount1;
