name: Publish image

description: "Publishes a docker image to GitHub Container Registry"

inputs:
  dockerImageBaseName:
    description: "Base image name for docker images"
    required: true
  dockerfile:
    description: "Path to Dockerfile"
    required: false
    default: "Dockerfile"
  context:
    description: "Docker build context"
    required: false
    default: "."
  imageTag:
    description: "Version image tag"
    required: true
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.GITHUB_TOKEN }}

    - name: Push image to registry
      shell: bash
      run: |
        # Construct the image tag using the Git hash
        IMAGE="${{ inputs.dockerImageBaseName }}:${{ inputs.imageTag }}"
        docker build "${{ inputs.context }}" --file "${{ inputs.dockerfile }}" --tag $IMAGE
        docker push $IMAGE
