name: Release version

description: "Deploys new version of the application to Azure"

inputs:
  region:
    description: "Azure region to deploy to"
    required: true
  imageTag:
    description: "Version image tag to release"
  environment:
    description: "Github environment to deploy from"
    required: true
  AZURE_SUBSCRIPTION_ID:
    description: "Subscription ID for the service principal"
    required: true
  AZURE_ENVIRONMENT_KEY_VAULT_NAME:
    description: "Name of the key vault"
    required: true
  AZURE_CLIENT_ID:
    description: "Client ID for the service principal"
    required: true
  AZURE_TENANT_ID:
    description: "Tenant ID for the service principal"
    required: true
  AZURE_NAME_PREFIX:
    description: "Prefix for all resources"
    required: true
  PLATFORM_BASE_URL:
    description: "Base url for Altinn platform"
    required: true
  STORAGE_ACCOUNT_NAME:
    description: "Name of the storage account used for attachments"
    required: true
  CORRESPONDENCE_BASE_URL:
    description: "Base url for callbacks to Correspondence"
  CONTACT_RESERVATION_REGISTRY_BASE_URL:
    description: "Contact Reservation Registry Base URL"
  DIALOGPORTEN_ISSUER:
    description: "Issuer for Dialogporten integration used to support ID"
    required: true
  IDPORTEN_ISSUER:
    description: "Issuer for Maskinporten integration used for IDPorten auth"
    required: true
  SBL_BRIDGE_BASE_URL:
    description: "Base url for SBL Bridge"
    required: true
  MASKINPORTEN_TOKEN_EXCHANGE_ENVIRONMENT:
    description: "Environment for Maskinporten token exchange"
    required: false
    default: ""
  MASKINPORTEN_ENVIRONMENT:
    description: "Maskinporten environment"
    required: true
    default: ""


runs:
  using: "composite"
  steps:
    - name: "Checkout repository"
      uses: actions/checkout@v4

    - name: OIDC Login to Azure Public Cloud
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.AZURE_CLIENT_ID }}
        tenant-id: ${{ inputs.AZURE_TENANT_ID }}
        subscription-id: ${{ inputs.AZURE_SUBSCRIPTION_ID }}

    - name: Upsert App Registration
      uses: azure/CLI@v2
      id: upsert-app-registration
      with:
        timeout-minutes: 3
        azcliversion: 2.56.0
        inlineScript: |
          chmod +x ./upsert-app-registration.sh
          while IFS= read -r line; do
            echo "$line" >> $GITHUB_ENV
          done < <(./upsert-app-registration.sh "EventGridSecuredAPI")

    - name: Deploy app
      uses: azure/arm-deploy@v2
      id: deploy
      env:
        IMAGE_TAG: ${{ inputs.imageTag }}
        ENVIRONMENT: ${{ inputs.environment }}
        KEY_VAULT_NAME: ${{ inputs.AZURE_ENVIRONMENT_KEY_VAULT_NAME }}
        KEY_VAULT_URL: https://${{ inputs.AZURE_ENVIRONMENT_KEY_VAULT_NAME }}.vault.azure.net
        NAME_PREFIX: ${{ inputs.AZURE_NAME_PREFIX }}
        CLIENT_ID: ${{ inputs.AZURE_CLIENT_ID }}
        TENANT_ID: ${{ inputs.AZURE_TENANT_ID }}
        PLATFORM_BASE_URL: ${{ inputs.PLATFORM_BASE_URL }}
        STORAGE_ACCOUNT_NAME: ${{ inputs.STORAGE_ACCOUNT_NAME }}
        CORRESPONDENCE_BASE_URL: ${{ inputs.CORRESPONDENCE_BASE_URL }}
        CONTACT_RESERVATION_REGISTRY_BASE_URL: ${{ inputs.CONTACT_RESERVATION_REGISTRY_BASE_URL }}
        DIALOGPORTEN_ISSUER: ${{ inputs.DIALOGPORTEN_ISSUER }}
        IDPORTEN_ISSUER: ${{ inputs.IDPORTEN_ISSUER }}
        SBL_BRIDGE_BASE_URL: ${{ inputs.SBL_BRIDGE_BASE_URL }}
        MASKINPORTEN_TOKEN_EXCHANGE_ENVIRONMENT: ${{ inputs.MASKINPORTEN_TOKEN_EXCHANGE_ENVIRONMENT }}
        MASKINPORTEN_ENVIRONMENT: ${{ inputs.MASKINPORTEN_ENVIRONMENT }}
        EVENT_GRID_CLIENT_ID: ${{ env.EVENT_GRID_CLIENT_ID }}
        EVENT_GRID_TENANT_ID: ${{ env.EVENT_GRID_TENANT_ID }}
      with:
        scope: subscription
        subscriptionId: ${{ inputs.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ inputs.AZURE_NAME_PREFIX }}-rg
        template: ./.azure/applications/api/main.bicep
        deploymentMode: Incremental
        deploymentName: ${{ inputs.AZURE_NAME_PREFIX }}-${{ steps.get-version.outputs.imageTag }}
        region: ${{ inputs.region }}
        failOnStdErr: false
        parameters: ./.azure/applications/api/params.bicepparam

    - name: Verify deployment
      uses: azure/CLI@v2
      id: verify-deployment
      with:
        timeout-minutes: 3
        azcliversion: 2.56.0
        inlineScript: |
          chmod +x ./.github/tools/revisionVerifier.sh
          ./.github/tools/revisionVerifier.sh ${{ steps.deploy.outputs.revisionName }} ${{ inputs.AZURE_NAME_PREFIX }}-rg

    - name: Logout from azure
      shell: bash
      if: ${{failure() || success()}}
      continue-on-error: true
      run: az logout
