using System.Text.Json.Serialization;
using Altinn.Correspondence.Core.Models.Enums;

namespace Altinn.Correspondence.Core.Models.Notifications;

/// <summary>
/// A class representing a registered notification order with status information. 
/// </summary>
/// <remarks>
/// External representation to be used in the API.
/// </remarks>
public class NotificationOrderWithStatus
{
    /// <summary>
    /// Gets or sets the id of the notification order
    /// </summary>
    [JsonPropertyName("id")]
    [JsonPropertyOrder(1)]
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the senders reference of the notification
    /// </summary>
    [JsonPropertyName("sendersReference")]
    [JsonPropertyOrder(2)]
    public string? SendersReference { get; set; }

    /// <summary>
    /// Gets or sets the requested send time of the notification
    /// </summary>
    [JsonPropertyName("requestedSendTime")]
    [JsonPropertyOrder(3)]
    public DateTime RequestedSendTime { get; set; }

    /// <summary>
    /// Gets or sets the short name of the creator of the notification order
    /// </summary>
    [JsonPropertyName("creator")]
    [JsonPropertyOrder(4)]
    public string Creator { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the date and time of when the notification order was created
    /// </summary>
    [JsonPropertyName("created")]
    [JsonPropertyOrder(5)]
    public DateTime Created { get; set; }

    /// <summary>
    /// Gets or sets the preferred notification channel of the notification order
    /// </summary>
    [JsonPropertyName("notificationChannel")]
    [JsonConverter(typeof(JsonStringEnumConverter))]
    [JsonPropertyOrder(6)]
    public NotificationChannel NotificationChannel { get; set; }

    /// <summary>
    /// Gets or sets whether notifications generated by this order should ignore KRR reservations
    /// </summary>
    [JsonPropertyName("ignoreReservation")]
    [JsonPropertyOrder(7)]
    public bool? IgnoreReservation { get; set; }

    /// <summary>
    /// Gets or sets the id of the resource that the notification is related to
    /// </summary>
    [JsonPropertyName("resourceId")]
    [JsonPropertyOrder(8)]
    public string? ResourceId { get; set; }

    /// <summary>
    /// Gets or sets the condition endpoint used to check the send condition
    /// </summary>
    [JsonPropertyName("conditionEndpoint")]
    [JsonPropertyOrder(9)]
    public Uri? ConditionEndpoint { get; set; }
    /// <summary>
    /// Gets or sets the processing status of the notication order
    /// </summary>
    [JsonPropertyName("processingStatus")]
    [JsonPropertyOrder(10)]
    public StatusExt ProcessingStatus { get; set; } = new();

    /// <summary>
    /// Gets or sets the summary of the notifiications statuses
    /// </summary>
    [JsonPropertyName("notificationsStatusSummary")]
    [JsonPropertyOrder(11)]
    public NotificationsStatusSummary? NotificationsStatusSummary { get; set; }
}