# File: .github/actions/deploy-to-environment/action.yml
name: "Deploy to Environment"
description: "Deploy application to a specified environment"

inputs:
  environment:
    description: "Environment to deploy to (e.g., test, staging, production)"
    required: true
  imageTag:
    description: "Docker image tag to deploy"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Update infrastructure
      uses: ./.github/actions/update-infrastructure
      with:
        region: "norwayeast"
        environment: ${{ inputs.environment }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_NAME_PREFIX: ${{ secrets.AZURE_NAME_PREFIX }}
        AZURE_ENVIRONMENT_KEY_VAULT_NAME: ${{ secrets.AZURE_ENVIRONMENT_KEY_VAULT_NAME }}
        AZURE_TEST_ACCESS_CLIENT_ID: ${{ secrets.AZURE_TEST_ACCESS_CLIENT_ID }}
        AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
        MASKINPORTEN_JWK: ${{ secrets.MASKINPORTEN_JWK }}
        MASKINPORTEN_CLIENT_ID: ${{ secrets.MASKINPORTEN_CLIENT_ID }}
        PLATFORM_SUBSCRIPTION_KEY: ${{ secrets.PLATFORM_SUBSCRIPTION_KEY }}
        ACCESS_MANAGEMENT_SUBSCRIPTION_KEY: ${{ secrets.ACCESS_MANAGEMENT_SUBSCRIPTION_KEY }}
        SLACK_URL: ${{ secrets.SLACK_URL }}
        IDPORTEN_CLIENT_ID: ${{ secrets.IDPORTEN_CLIENT_ID }}
        IDPORTEN_CLIENT_SECRET: ${{ secrets.IDPORTEN_CLIENT_SECRET }}

    - name: Migrate database
      uses: ./.github/actions/migrate-database
      with:
        region: "norwayeast"
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        environment: ${{ inputs.environment }}
        AZURE_NAME_PREFIX: ${{ secrets.AZURE_NAME_PREFIX }}
        AZURE_ENVIRONMENT_KEY_VAULT_NAME: ${{ secrets.AZURE_ENVIRONMENT_KEY_VAULT_NAME }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}

    - name: Release version
      uses: ./.github/actions/release-version
      with:
        region: "norwayeast"
        environment: ${{ inputs.environment }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_NAME_PREFIX: ${{ secrets.AZURE_NAME_PREFIX }}
        AZURE_ENVIRONMENT_KEY_VAULT_NAME: ${{ secrets.AZURE_ENVIRONMENT_KEY_VAULT_NAME }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        PLATFORM_BASE_URL: ${{ secrets.PLATFORM_BASE_URL }}
        CORRESPONDENCE_BASE_URL: ${{ secrets.CORRESPONDENCE_BASE_URL }}
        STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
        imageTag: ${{ inputs.imageTag }}
        DIALOGPORTEN_ISSUER: ${{ secrets.DIALOGPORTEN_ISSUER }}
        IDPORTEN_ISSUER: ${{ secrets.IDPORTEN_ISSUER }}