apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      kind: OCIRepository
      name: broker-app-sync
    patch: |-
      - op: replace
        path: /spec/ref/tag
        value: prod
  - target:
      kind: OCIRepository
      name: correspondence-app-sync
    patch: |-
      - op: replace
        path: /spec/ref/tag
        value: prod
