name: Deploy app
env:
  AZ_CLI_VERSION: 2.56.0
on:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_ENVIRONMENT_KEY_VAULT_NAME:
        required: true
      AZURE_NAME_PREFIX:
        required: true
      AZURE_MIGRATION_STORAGE_ACCOUNT_NAME:
        required: true
    inputs:
      region:
        required: true
        type: string
      environment:
        required: true
        type: string
      version:
        description: "Current version to use as tag"
        required: true
        type: string
      ref:
        description: "The branch or tag ref to deploy. Using default checkout ref if not provided."
        required: false
        default: ${{ github.ref }}
        type: string
      migrate:
        description: "Should migration be run before deploying"
        required: true
        type: string
jobs:
  deploy-app:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Checkout Altinn Correspondence repository"
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
      - name: OIDC Login to Azure Public Cloud
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy migration job (${{ inputs.environment }})
        uses: azure/arm-deploy@v2
        id: migration-job
        env:
          KEY_VAULT_NAME: ${{ secrets.AZURE_ENVIRONMENT_KEY_VAULT_NAME }}
          KEY_VAULT_URL: https://${{ secrets.AZURE_ENVIRONMENT_KEY_VAULT_NAME }}.vault.azure.net
          NAME_PREFIX: ${{ secrets.AZURE_NAME_PREFIX }}
          APP_VERSION: ${{ inputs.version }}
          CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ENVIRONMENT: ${{ inputs.environment }}
        with:
          scope: resourcegroup
          template: ./.azure/applications/migration/main.bicep
          resourceGroupName: ${{ secrets.AZURE_NAME_PREFIX }}-rg
          deploymentMode: Incremental
          deploymentName: migration-${{ inputs.version }}
          region: ${{ inputs.region }}
          failOnStdErr: false
          parameters: ./.azure/applications/migration/params.bicepparam

      - name: Install EF Core CLI
        run: dotnet tool install dotnet-ef --global
        shell: bash

      - name: Create migration script
        run: | 
            dotnet ef migrations bundle --project ./src/Altinn.Correspondence.Persistence --startup-project ./src/Altinn.Correspondence.API --self-contained -r linux-x64 -o ./src/Altinn.Correspondence.Persistence/Migrations/bundle.exe
      
      - name: Upload Migration Files to Azure File Share
        uses: azure/CLI@v2
        with:
          azcliversion: ${{ env.AZ_CLI_VERSION }}
          inlineScript: |
            az storage copy --source ./src/Altinn.Correspondence.Persistence/Migrations/bundle.exe --destination https://${{ secrets.AZURE_MIGRATION_STORAGE_ACCOUNT_NAME }}.file.core.windows.net/migrations --recursive
            az storage copy --source ./src/Altinn.Correspondence.API/appsettings.json --destination https://${{ secrets.AZURE_MIGRATION_STORAGE_ACCOUNT_NAME }}.file.core.windows.net/migrations --recursive

      - name: Start migration job
        uses: azure/CLI@v2
        with:
          azcliversion: ${{ env.AZ_CLI_VERSION }}
          inlineScript: |
            az containerapp job start -n ${{ steps.migration-job.outputs.name }} -g ${{ secrets.AZURE_NAME_PREFIX }}-rg

      - name: Verify migration
        uses: azure/CLI@v2
        id: verify-migration
        timeout-minutes: 3
        with:
          azcliversion: ${{ env.AZ_CLI_VERSION }}
          inlineScript: |
            chmod +x ./.github/tools/containerAppJobVerifier.sh
            ./.github/tools/containerAppJobVerifier.sh ${{ steps.migration-job.outputs.name }} '${{ secrets.AZURE_NAME_PREFIX }}-rg' ${{ inputs.version }}

      - name: Deploy app (${{ inputs.environment }})
        uses: azure/arm-deploy@v2
        id: deploy
        env:
          IMAGE_TAG: ${{ inputs.version }}
          ENVIRONMENT: ${{ inputs.environment }}
          KEY_VAULT_NAME: ${{ secrets.AZURE_ENVIRONMENT_KEY_VAULT_NAME }}
          KEY_VAULT_URL: https://${{ secrets.AZURE_ENVIRONMENT_KEY_VAULT_NAME }}.vault.azure.net
          NAME_PREFIX: ${{ secrets.AZURE_NAME_PREFIX }}
          CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_NAME_PREFIX }}-rg
          template: ./.azure/applications/api/main.bicep
          deploymentMode: Incremental
          deploymentName: ${{ secrets.AZURE_NAME_PREFIX }}-${{ inputs.version }}
          region: ${{ inputs.region }}
          failOnStdErr: false
          parameters: ./.azure/applications/api/params.bicepparam

      - name: Verify deployment
        uses: azure/CLI@v2
        id: verify-deployment
        timeout-minutes: 3
        with:
          azcliversion: ${{ env.AZ_CLI_VERSION }}
          inlineScript: |
            chmod +x ./.github/tools/revisionVerifier.sh
            ./.github/tools/revisionVerifier.sh ${{ steps.deploy.outputs.revisionName }} ${{ secrets.AZURE_NAME_PREFIX }}-rg

      - name: Logout from azure
        if: ${{failure() || success()}}
        continue-on-error: true
        run: az logout
