name: Deploy to environment

on:
  push:
    branches: [ fix/upload-and-download-artifact-for-publishing ]  # Trigger only on this branch
  workflow_call:
    inputs:
      environment:
        type: string
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Environment to deploy to"
        options:
          - test
          - staging
          - production

jobs:
  get-version: 
    name: Get version
    runs-on: ubuntu-latest
    outputs:
      imageTag: ${{ steps.get-version.outputs.imageTag }}
    permissions: 
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: "Get current version"
        uses: ./.github/actions/get-current-version
        id: get-version
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [get-version]
    permissions: 
      packages: write
      contents: read
    steps:        
      - uses: actions/checkout@v4
      - name: "Publish image"
        uses: ./.github/actions/publish-image
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          dockerImageBaseName: ghcr.io/altinn/altinn-correspondence
          imageTag: ${{ needs.get-version.outputs.imageTag }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [get-version]
    environment: ${{ inputs.environment }}
    permissions: 
      id-token: write
      contents: read

    steps:
    - name: Deploy to environment
      uses: ./.github/actions/deploy-to-environment
      with:
        environment: ${{ inputs.environment }}
        imageTag: ${{ needs.get-version.outputs.imageTag }}