name: Build correspondence sync image

env:
  ARTIFACT_NAME: corr/correspondence-sync
  DOCKER_IMAGE_BASE_NAME: altinncr.azurecr.io/corr/correspondence-sync

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'flux/correspondence/**'
      - '.github/workflows/publish-correspondence-sync.yml'
    tags:
      - 'corr-sync-*'

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build latest
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Login to ACR
        shell: bash
        run: |
          registry_host="${DOCKER_IMAGE_BASE_NAME%%/*}"
          acr_name="${registry_host%%.azurecr.io}"
          az acr login --name "$acr_name"
      - name: Get short sha
        id: get_sha
        run: echo "short_sha=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
      - name: Push image to registry
        shell: bash
        run: |
          IMAGE="${{ env.DOCKER_IMAGE_BASE_NAME }}:${{ steps.get_sha.outputs.short_sha }}"
          docker build . --tag $IMAGE
          docker push $IMAGE
      - name: Build and push latest artifact
        uses: Altinn/altinn-platform/actions/flux/build-push-image@8d4e42eae11efbc3a159aa62fe15ed49954d9df9 # main
        with:
          image_name: ${{ env.ARTIFACT_NAME }}
          tag: ${{ steps.get_sha.outputs.short_sha }}
          acr_name: altinncr
          workdir: ./flux/correspondence
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_app_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
  deploy_test:
    name: Deploy to test
    runs-on: ubuntu-latest
    needs: [ build ]
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Get short sha
        id: get_tags
        run: |
          echo "short_sha=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
      - name: Re-tag existing image with test
        uses: Altinn/altinn-platform/actions/flux/retag-image@8d4e42eae11efbc3a159aa62fe15ed49954d9df9 # main
        with:
          image_name: ${{ env.ARTIFACT_NAME }}
          from_tag: ${{ steps.get_tags.outputs.short_sha }}
          tag: "test"
          workdir: ./flux/correspondence
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_app_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}

  deploy_staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    needs: [ deploy_test ]
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Get short sha
        id: get_tags
        run: |
          echo "short_sha=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
      - name: Re-tag existing image with staging
        uses: Altinn/altinn-platform/actions/flux/retag-image@8d4e42eae11efbc3a159aa62fe15ed49954d9df9 # main
        with:
          image_name: ${{ env.ARTIFACT_NAME }}
          from_tag: ${{ steps.get_tags.outputs.short_sha }}
          tag: "staging"
          workdir: ./flux/correspondence
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_app_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}

  deploy_production:
    name: Deploy to production
    runs-on: ubuntu-latest
    needs: [ deploy_staging ]
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Get short sha
        id: get_tags
        run: |
          echo "short_sha=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
      - name: Re-tag existing image with prod
        uses: Altinn/altinn-platform/actions/flux/retag-image@8d4e42eae11efbc3a159aa62fe15ed49954d9df9 # main
        with:
          image_name: ${{ env.ARTIFACT_NAME }}
          from_tag: ${{ steps.get_tags.outputs.short_sha }}
          tag: "prod"
          workdir: ./flux/correspondence
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_app_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}

  deploy_other_environments:
    name: Deploy to other environments (${{ matrix.environment }})
    runs-on: ubuntu-latest
    needs: [ deploy_test ]
    strategy:
      max-parallel: 1
      matrix:
        environment: [ yt01, at22, at23, at24 ]
    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Get short sha
        id: get_tags
        run: |
          echo "short_sha=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
      - name: Re-tag existing image with environment tag
        uses: Altinn/altinn-platform/actions/flux/retag-image@8d4e42eae11efbc3a159aa62fe15ed49954d9df9 # main
        with:
          image_name: ${{ env.ARTIFACT_NAME }}
          from_tag: ${{ steps.get_tags.outputs.short_sha }}
          tag: ${{ matrix.environment }}
          workdir: ./flux/correspondence
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_app_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
