name: Build syncroot image

env:
  ARTIFACT_NAME: corr/syncroot

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'flux/syncroot/**'
      - '.github/workflows/publish-syncroot.yml'
    tags:
      - 'syncroot-*'

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build latest from main
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Validate syncroot image
        uses: Altinn/altinn-platform/actions/flux/verify-syncroot@015e4f2b2fad90ac188e0e401c30f79de8523e1a # main
        with:
          workdir: ./flux/syncroot
      - name: Build and push latest artifact
        uses: Altinn/altinn-platform/actions/flux/build-push-image@015e4f2b2fad90ac188e0e401c30f79de8523e1a # main
        with:
          image_name: ${{ env.ARTIFACT_NAME }}
          tag: at22
          workdir: ./flux/syncroot
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_app_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
  release:
    name: Build release from tag
    runs-on: ubuntu-latest
    needs: [ build ]
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Get tag short sha
        id: get_tags
        run: |
          echo "tag=${GITHUB_REF/refs\/tags\/syncroot-/}" >> $GITHUB_OUTPUT
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Re-tag existing image with semver
        uses: Altinn/altinn-platform/actions/flux/retag-image@015e4f2b2fad90ac188e0e401c30f79de8523e1a # main
        with:
          image_name: ${{ env.ARTIFACT_NAME }}
          from_tag: ${{ steps.get_tags.outputs.short_sha }}
          tag: ${{ steps.get_tags.outputs.tag }}
          workdir: ./flux/syncroot
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_app_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      - name: Re-tag existing image with at23
        uses: Altinn/altinn-platform/actions/flux/retag-image@015e4f2b2fad90ac188e0e401c30f79de8523e1a # main
        with:
          image_name: ${{ env.ARTIFACT_NAME }}
          from_tag: ${{ steps.get_tags.outputs.short_sha }}
          tag: "at23"
          workdir: ./flux/syncroot
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_app_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      - name: Re-tag existing image with at24
        uses: Altinn/altinn-platform/actions/flux/retag-image@015e4f2b2fad90ac188e0e401c30f79de8523e1a # main
        with:
          image_name: ${{ env.ARTIFACT_NAME }}
          from_tag: ${{ steps.get_tags.outputs.short_sha }}
          tag: "at24"
          workdir: ./flux/syncroot
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_app_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      - name: Re-tag existing image with tt02
        uses: Altinn/altinn-platform/actions/flux/retag-image@015e4f2b2fad90ac188e0e401c30f79de8523e1a # main
        with:
          image_name: ${{ env.ARTIFACT_NAME }}
          from_tag: ${{ steps.get_tags.outputs.short_sha }}
          tag: "tt02"
          workdir: ./flux/syncroot
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_app_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      - name: Re-tag existing image with yt01
        uses: Altinn/altinn-platform/actions/flux/retag-image@015e4f2b2fad90ac188e0e401c30f79de8523e1a # main
        with:
          image_name: ${{ env.ARTIFACT_NAME }}
          from_tag: ${{ steps.get_tags.outputs.short_sha }}
          tag: "yt01"
          workdir: ./flux/syncroot
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_app_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      - name: Re-tag existing image with prod
        uses: Altinn/altinn-platform/actions/flux/retag-image@015e4f2b2fad90ac188e0e401c30f79de8523e1a # main
        with:
          image_name: ${{ env.ARTIFACT_NAME }}
          from_tag: ${{ steps.get_tags.outputs.short_sha }}
          tag: "prod"
          workdir: ./flux/syncroot
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_app_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
