name: Publish test branch

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: test
    permissions: 
      id-token: write
      contents: read
      packages: write
    steps:        
        - uses: actions/checkout@v4
        - name: Get version
          id: get-version
          uses: ./.github/actions/get-current-version
        - name: "Publish image"
          uses: ./.github/actions/publish-image
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            dockerImageBaseName: ghcr.io/altinn/altinn-correspondence
            imageTag: ${{ steps.get-version.outputs.imageTag }}
        - name: Release version
          uses: ./.github/actions/release-version
          with:
            region: norwayeast
            environment: test
            imageTag: ${{ steps.get-version.outputs.imageTag }}
            AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            AZURE_NAME_PREFIX: ${{ secrets.AZURE_NAME_PREFIX }}
            AZURE_ENVIRONMENT_KEY_VAULT_NAME: ${{ secrets.AZURE_ENVIRONMENT_KEY_VAULT_NAME }}
            AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            PLATFORM_BASE_URL: ${{ secrets.PLATFORM_BASE_URL }}
            LEGACY_BASE_URL: ${{ secrets.LEGACY_BASE_URL }}
            CORRESPONDENCE_BASE_URL: ${{ secrets.CORRESPONDENCE_BASE_URL }}
            STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
            DIALOGPORTEN_ISSUER: ${{ secrets.DIALOGPORTEN_ISSUER }}
            IDPORTEN_ISSUER: ${{ secrets.IDPORTEN_ISSUER }}
          