name: Build correspondence sync image

env:
  ARTIFACT_NAME: corr/correspondence-sync

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'flux/correspondence/**'
      - '.github/workflows/publish-correspondence-sync.yml'
    tags:
      - 'corr-sync-*'

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build lates
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Build and push latest artifact
        uses: Altinn/altinn-platform/actions/flux/build-push-image@015e4f2b2fad90ac188e0e401c30f79de8523e1a # main
        with:
          image_name: ${{ env.ARTIFACT_NAME }}
          tag: main
          workdir: ./flux/correspondence
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_app_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
  release:
    name: Build release from tag
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Get tag short sha
        id: get_tags
        run: |
          echo "tag=${GITHUB_REF/refs\/tags\/corr-sync-/}" >> $GITHUB_OUTPUT
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Re-tag existing image with semver
        uses: Altinn/altinn-platform/actions/flux/retag-image@015e4f2b2fad90ac188e0e401c30f79de8523e1a # main
        with:
          image_name: ${{ env.ARTIFACT_NAME }}
          from_tag: ${{ steps.get_tags.outputs.short_sha }}
          tag: ${{ steps.get_tags.outputs.tag }}
          workdir: ./flux/correspondence
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_app_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      - name: Re-tag existing image with prod
        uses: Altinn/altinn-platform/actions/flux/retag-image@015e4f2b2fad90ac188e0e401c30f79de8523e1a # main
        with:
          image_name: ${{ env.ARTIFACT_NAME }}
          from_tag: ${{ steps.get_tags.outputs.short_sha }}
          tag: "prod"
          workdir: ./flux/correspondence
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_app_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
