name: Test Performance

on:
    push:
        branches:
            - performance*

jobs:
    test-performance:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Print
              run:
                  echo "Hello, world!"


            # Add your test steps here
            # ...
